---
- name: set 755 permission on all website folders
  command: find {{ public_path }} -type d -exec chmod 755 {} \;


- name: set 644 permission on all website files
  command: find {{ public_path }} -type f -exec chmod 644 {} \;
