---
- name: website
  hosts: all
  user: root
  become: true
  roles:
  - website
  handlers:
  - include: handlers/main.yml
  vars_files:
  - vars/local.yml
  - vars/backups.yml
  - vars/nginx.yml
  - vars/csr.yml
  - vars/logging.yml
  - vars/website.yml
  - vars/secrets.yml
  - vars/vault.yml
