---
- name: copy https serverblock
  template: src=templates/nginx/https.conf.j2
            dest={{ nginx_sites_available }}{{ serverblock }}
            owner=root
            group=root
            mode=0644
  notify: restart nginx


- name: make https serverblock symbolic link
  file: src={{ nginx_sites_available }}{{ serverblock }}
        dest={{ nginx_sites_enabled }}{{ serverblock }}
        owner=root
        group=root
        state=link
  notify: restart nginx
