---
- name: import website in rds database
  mysql_db: name={{ db_name }}
            login_host={{ mysql_rds_host }}
            login_port={{ mysql_rds_login_port }}
            login_user={{ rds_username }}
            login_password={{ rds_password }}
            target={{ mysql_backup_path }}database.sql
            state=import