---
## User
user: user
user_home: "/home/{{ user }}"

## Nginx paths
nginx_user: www-data
nginx_ssl: /etc/nginx/ssl/
nginx_conf_server: /etc/nginx/conf/server/
nginx_sites_available: /etc/nginx/sites-available/
nginx_sites_enabled: /etc/nginx/sites-enabled/

## HHVM links
hhvm_tcp_port: 8000
hhvm_global_connection: "127.0.0.1:{{ hhvm_tcp_port }}"

## PHP links
php_tcp_port: 9000
php_global_connection: "127.0.0.1:{{ php_tcp_port }}"
#php_global_connection: /var/run/php-fpm.sock

## MySQL links
mysql_port: 3306
mysql_host: localhost

## RDS links
mysql_rds_host: "{{ aws_region }}.rds.amazonaws.com:{{ mysql_port }}"
mysql_rds_login_port: "{{ mysql_port }}"

## Redis
redis_host: 127.0.0.1
redis_port: 6379
redis_user: redis
