---
- name: download the archive
  get_url: url=http://wordpress.org/latest.zip
           dest={{ server_path }}latest.zip
           force=yes


- name: unpack the archive
  unarchive: src={{ server_path }}latest.zip dest={{ server_path }} creates={{ public_path }}wp-admin/ copy=no


- name: rename wordpress folder
  command: mv wordpress public chdir={{ server_path }} creates={{ public_path }}wp-admin/


- name: delete the archive
  file: path={{ server_path }}latest.zip
        state=absent


- name: delete the wp config sample
  file: path={{ public_path }}wp-config-sample.php
        state=absent
