---
- name: redis plugin
  subversion: repo=http://plugins.svn.wordpress.org/{{ item.name }}/{{ item.version }}/
              dest={{ publicpath }}wp-content/plugins/{{ item.name }}

  with_items:

# https://wordpress.org/plugins/wp-redis/developers/
#
    - {name: wp-redis, version: tags/0.1}


- name: enable redis
  file: src={{ publicpath }}wp-content/plugins/wp-redis/object-cache.php
        dest={{ publicpath }}wp-content/object-cache.php
        owner={{ nginx_user }}
        group={{ nginx_user }}
        mode=0644
